bookshopper/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.conf import settings

from haystack.views import SearchView

#from sastakart.views import *
#from shop.views import *
from querydata.views import *

urlpatterns = [
#    url(r'^', include('django.contrib.auth.urls')),
#    url(r'^', include('sastakart.urls',namespace='sastakart')),
#    url(r'^$', home, name='home'),
#    url(r'^search/$', search, name='search'),
#    url(r'^$', include('searchableselect.urls')),
#    url(r'',include('querydata.urls')),
    url(r'^', include('querydata.urls',namespace='querydata')),

#    url('^search/', include('searchableselect.urls')),
#    url(r'^search/', include('select2.urls')),
#    url(r'^search/', search, name='search'),
#    url(r'^search/', include('haystack.urls')),
#    url(r'^(?P<cat_slug>[-\w]+)/(?P<asin>[-\w]{10})/$', product_page, name='product_page'),
#    url(r'^(?P<slug>[-\w]+)/$', category_view, name='category_view'),
#    url(r'^page/(?P<slug>[-\w]+)/$', static_page, name='static_page'),
#    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

querydata/urls.py
from django.conf.urls import *
from views import *


urlpatterns = [
#    url(r'^$', SearchFormView.as_view(), name='home'),
#    url(r'^$', MainView.as_view(), name='home'),
    url(r'^$', home, name='home'),
#    url(r'^$', CountryAutocomplete.as_view(), name='home'),
#    url(r'^searchbar/$', SearchBarView.as_view(), name='searchbar'),
#    url(r'^search/$', BookFormView.as_view(), name='search'),
    url(r'^search/$', search, name='search'),
#    url(r'^search/(?P<keyword>[a-zA-Z0-9!@#$&()\\ -`.+,/\"]*)/(?P<page>[0-9]*)/$', SearchResultView.as_view(), name='search'),
    #url(r'^search/(?P<title>[a-zA-Z0-9!@#$&()\\ -`.+,/\"]*)/(?P<author>[a-zA-Z0-9!@#$&()\\ -`.+,/\"]*)/$', SearchResultView.as_view(), name='search'),
    #url(r'^search/(?P<keyword>[a-zA-Z0-9!@#$&()\\ -`.+,/\"]*)/(?P<page>[0-9]*)/$', search, name='search'),
    #url(r'^search/(?P<title>\w+)/(?P<author_name>\w+)/$', search, name='search'),
    url(r'^product/(?P<id>[a-zA-Z0-9!@#$&()\\ -`.+,/\"]*)/$', ProductView.as_view(), name='product'),
    #url(r'^product/(?P<slug>[-\w]+)$', ProductView.as_view(), name='product'),
    url(r'^faq/$', FAQView.as_view(), name='faq'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    #url(r'^robots.txt/$',RobotsView.as_view(content_type='text/plain')),
]

templates/search/amazon_custom_link.html
<div class="amazon_custom_link">
<a href="http://www.amazon.com/gp/redirect.html?ie=UTF8&location={{ amazon_custom_link_url|urlencode }}&tag={{ amazon_affiliates_id }}&linkCode=ur2&camp=1789&creative=9325">{{ amazon_custom_link_title }}</a><img src="http://www.assoc-amazon.com/e/ir?t={{ amazon_affiliates_id }}&amp;l=ur2&amp;o=1" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
</div>

templates/search/amazon_search.html
<div class="amazon_search">
<a href="http://www.amazon.com/gp/search?ie=UTF8&keywords={{ amazon_search_terms|urlencode }}&tag={{ amazon_affiliates_id }}&index=blended&linkCode=ur2&camp=1789&creative=9325">{{ amazon_search_title }}</a><img src="http://www.assoc-amazon.com/e/ir?t={{ amazon_affiliates_id }}&amp;l=ur2&amp;o=1" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
</div>

templates/search/search.html
{% extends 'base.html' %}

{% block content %}
<div class="navigation" >
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home'  %}" style="font-family: 'Lobster';">Book Shopper</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" style="font-size:25px;">
          <li><a href="{% url 'home'  %}" data-toggle="tooltip" data-placement="bottom" title="property"><i class="fa fa-home"></i></a></li>
      </ul>
      <div class="col-sm-3 col-md-3 pull-right">
        <form action="" class="navbar-form navbar-right" type="get" action="\search">
          <div class="input-group">
            <input type="text" name="q" placeholder="Search..." class="form-control" />
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit" style="font-size:20px">
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </nav>
</div>

{% if query %}
  <div class="container" style="margin-top: 1cm;">
    {% for result in page.object_list %}
      <div class="well">
        <div class="media">
          <a class="pull-left" href="#">
            <img class="media-object"  src="{{ result.object.small_url }}">
          </a>
          <div class="media-body">
          <h4 class="media-heading">{{ result.object.title }}</h4>
          <a href="{{result.object.link}}" role="button" class="btn btn-success btn-large pull-right"> Details</a>
          <p>{{ result.object.descript }}</p>
          <ul class="list-inline list-unstyled">
            <li>
              <span><i class="fa fa-calendar"></i> {{result.object.time}}, {{result.object.pub_date}} </span>
            </li>
            <li>|</li>
              <span><i class="fa fa-map-marker"></i> {{ result.object.author_name }}</span>
            <li>|</li>
            <li>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star-empty"></span>
            </li>
            <li>|</li>
            <li>
            <!-- Use Font Awesome http://fortawesome.github.io/Font-Awesome/ -->
              <span><i class="fa fa-money"> {{result.object.price}}</i></span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    {% empty %}
    <h1 style="font-size:55px;text-align: center;">No Result found </h1>
    {% endfor %}
  </div>

{% if page.has_previous or page.has_next %}
  <div>
  {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
  |
  {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
  </div>
{% endif %}

{% else %}
{# Show some example queries to run, maybe query syntax, something else? #}
{% endif %}


<div class="container">

    <hr>

    <div class="row">
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading"><h3>Hello.</h3></div>
            <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
            Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
            dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
            Aliquam in felis sit amet augue.
            </div>
          </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
            <div class="panel-heading"><h3>Hello.</h3></div>
            <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
            Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
            dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
            Aliquam in felis sit amet augue.
            </div>
          </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
            <div class="panel-heading"><h3>Hello.</h3></div>
            <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
            Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
            dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
            Aliquam in felis sit amet augue.
            </div>
          </div>
        </div>
    </div>

{% endblock %}

templates/search/search_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <title>BookShopper</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="keywords" content="">

    <!-- styles -->
    <link href="/static/css/bootstrap.css" rel="stylesheet" />
    <link href="/static/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/static/css/animate.min.css" rel="stylesheet" />

    <!-- theme stylesheet -->
    <link href="/static/css/style.default.css" rel="stylesheet" />
    <!-- your stylesheet with modifications -->
    <link href="/static/css/custom.css" rel="stylesheet" />
    <link href="/static/css/skeleton.css" rel="stylesheet" />
    <link href="/static/css/results_page_v2.css" rel="stylesheet" />

    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>

    <link rel="shortcut icon" href="/static/favicon.png">
    <script src="/static/js/respond.min.js"></script>
</head>
<body>

<div id="top_level_div">

    <div class="navigation">
      <nav class="navbar navbar-default" role="navigation">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'querydata:home'  %}" style="font-family: 'Lobster';">Book Shopper</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav" style="font-size:25px;">
              <li><a href="{% url 'querydata:home'  %}" data-toggle="tooltip" data-placement="bottom" title="property"><i class="fa fa-home"></i></a></li>
              <li><a href="/admin/" data-toggle="tooltip" data-placement="bottom" title="property">Admin</a></li>
          </ul>

          <div class="navbar-collapse collapse right" id="search-not-mobile">
        <form class="navbar-form" action="{% url 'querydata:search' %}" role="search" method="POST">
            {% csrf_token %}
            <div class="input-group" style="width:25% ; right:28px; display:flex; position:absolute;">
            <input type="text" id="id_searchbar" name="search_text" class="form-control" placeholder="Search">
            <span class="input-group-btn">
            <button type="submit" id="id_searchbut" class="btn btn-primary" name="search_submit"><i class="fa fa-search"></i></button>
            </span>
            </div>
        </form>
    </div>

        </div>
      </nav>
    </div> <!--/.navigation -->

</div> <!-- /.top_level_div -->

<div id="all" style="padding-top: 105px;">
        {% block content %}
        {% endblock %}

         <div id="footer" data-animate="fadeInUp">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <h4>Pages</h4>
                    <ul>
                        <li><a href="{% url "querydata:about" %}">About us</a>
                        </li>
                        <li><a href="{% url "querydata:faq" %}">FAQ</a>
                        </li>
                        <li><a href="{% url "querydata:contact" %}">Contact us</a>
                        </li>
                    </ul>
                    <hr class="visible-xs visible-sm">
                </div>
                <!-- /.col-md-3 -->

                <div class="col-md-3 col-sm-6">
                    <h4>Top Books</h4>
                    <ul>
                        <li><a href="#" class="cat-anchor">Fiction</a>
                        </li>
                        <li><a href="#" class="cat-anchor">Fiction</a>
                        </li>
                        <li><a href="#" class="cat-anchor">Fiction</a>
                        </li>
                    </ul>
                    <hr class="hidden-md hidden-lg">

                </div>
                <!-- /.col-md-3 -->

                <div class="col-md-3 col-sm-6">
                    <h4>Where to find us</h4>
                    <p><strong>Company Name </strong>
                        <br>First Name
                        <br>Address
                        <br>Address
                        <br>City
                    </p>
               <!--     <a href="/static/contact.html">Go to contact page</a> -->
                    <hr class="hidden-md hidden-lg">
                </div>
                <!-- /.col-md-3 -->

                <div class="col-md-3 col-sm-6">
                    <h4>Get the latest discounts & coupons</h4>
                    <p class="text-muted">Latest discounts and coupons on Flipkart, Amazon, eBay and Snapdeal.</p>
                    <form>
                        <div class="input-group">
                            <input type="text" class="form-control">
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Subscribe!</button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </form>
                    <hr>

                    <h4>Stay in touch</h4>
                    <p class="social">
                        <a id="fb_footer" href="#" class="facebook external" data-animate-hover="shake"><i class="fa fa-facebook"></i></a>
                        <a id="twitter_footer" href="#" class="twitter external" data-animate-hover="shake"><i class="fa fa-twitter"></i></a>
                        <a id="instagram_footer" href="#" class="instagram external" data-animate-hover="shake"><i class="fa fa-instagram"></i></a>
                        <a id="gplus_footer" href="#" class="gplus external" data-animate-hover="shake"><i class="fa fa-google-plus"></i></a>
                        <a id="email_footer" href="#" class="email external" data-animate-hover="shake"><i class="fa fa-envelope"></i></a>
                    </p>

                </div>
                <!-- /.col-md-3 -->

            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->
    </div>
    <!-- /#footer -->

    <div id="copyright">
        <div class="container">
            <div class="col-md-12">
                <p class="text-center">© 2015 Bookshopper</p>

            </div>

        </div>
    </div>
</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-beta1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="/static/js/jquery-1.11.0.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/jquery.cookie.js"></script>
    <script src="/static/js/waypoints.min.js"></script>
    <script src="/static/js/modernizr.js"></script>
    <script src="/static/js/bootstrap-hover-dropdown.js"></script>
    <script src="/static/js/owl.carousel.min.js"></script>
    <script src="/static/js/front.js"></script>
    <script src="/static/js/custom_base.js"></script>
    <script type="text/javascript" src="/static/js/jqeye.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery("#pupil1").jqEye({width:12,height:12,radius:10});
            jQuery("#pupil2").jqEye({width:12,height:12,radius:9});
        });
    </script>

</div>
</body>
</html>

templates/search/search_compare.html
{% extends 'search/search_base.html' %}

{% block content %}

  <div class="container" style="margin-top: 1cm;">
    {% for item in book_entries %}
      <div class="well">
        <div class="media">
          <a class="pull-left" href="#">
            <img class="media-object"  src="{{ item.image_url }}">
          </a>
          <div class="media-body">
          <h4 class="media-heading"><a href="{{ item.link }}">{{ item.title }}</a></h4>
          <p>{{ item.descript }}</p>
          <ul class="list-inline list-unstyled">
            <li>
              <span><i class="fa fa-calendar"></i> {{ item.time }} {{ item.pub_date }} </span>
            </li>
            <li>|</li>
              <span><i class="fa fa-map-marker"></i> {{ item.author_name }}</span>
            <li>|</li>
            <li>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star"></span>
              <span class="glyphicon glyphicon-star-empty"></span>
            </li>
            <li>|</li>
            <li>
            <!-- Use Font Awesome http://fortawesome.github.io/Font-Awesome/ -->
              <span><i class="fa fa-money"> {{ item.price }}</i></span>
            </li>
            <li><a href="{{ item.link }}" role="button" class="btn btn-success"> Buy Now!</a></li>
          </ul>
        </div>
      </div>
    </div>
    {% empty %}
    <h1 style="font-size:55px;text-align: center;">No Result Found </h1>
    {% endfor %}
  </div>

{% if page.has_previous or page.has_next %}
  <div>
  {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
  |
  {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
  </div>
{% endif %}

{% endblock %}

templates/search/search_data.html
{% extends "search/search_base.html" %}

{% block content %}

<div id="content">
    <div class="container">

        <div class="col-md-12">

            <div class="box info-bar">
                <div class="row">
                    <div class="col-sm-12 col-md-4 books-showing">
                        Showing <strong>{{ books|length }}</strong> of <strong>{{ count_num }}</strong> books
                    </div>
                </div>
            </div>

            <div class="row books">

            {% for item in searchform %}
                <div class="col-md-3 col-sm-4">
                    <div class="product">
                        <div class="flip-container">
                            <div class="flipper">
                                <div class="front">
                                    <a href="{% url "querydata:product" id=item.slug %}">
                                        <div class="img_list">
                                        <img src="{{ item.small_url }}" alt="" style="position:absolute; top:0%; left:50%; margin-right:-50%; transform:translate(-50%,-50%); max-width: 160px; max-height: 140px;">
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="text">
                            <h3><a href="{% url "querydata:product" id=item.slug  %}">{{ item.title }}</a></h3>
                            <h3><a href="{% url "querydata:product" id=item.slug  %}">{{ item.author }}</a></h3>
                        </div> <!-- /.text -->
                    </div> <!-- /.product -->
                </div>

               {% endfor %}

            </div> <!-- /.books -->

            <div class="pages">

                <ul class="pagination">
                    {% if page > 1 %}
                    <li>
                    <a href="{% url "querydata:search" keyword=keyword page=1 %}"">&laquo;</a>
                    </li>
                    <li>
                    <a href="{% url "querydata:search" keyword=keyword page=page|add:"-1" %}"">&lt;</a>
                    </li>

                    {% endif %}

                    {% for i in arr_num_p %}
                    {% if i == page %}
                    <li class="active"><a href="javascript:void(0);">{{ i }}</a>
                    </li>
                    {% else %}
                    <li><a href="{% url "querydata:search" keyword=keyword page=i %}"">{{ i }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    {% if page < count_p %}
                    <li>
                    <a href="{% url "querydata:search" keyword=keyword page=page|add:"1" %}"">&gt;</a>
                    </li>
                    <li>
                    <a href="{% url "querydata:search" keyword=keyword page=count_p %}"">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </div>

        </div> <!-- /.col-md-9 -->

    </div> <!-- /.container -->
</div> <!-- /#content -->

{% endblock %}

templates/search/search_results_mobile.html
{% extends "skeleton.html" %}
{% block imports %}
{% load static %}
{% load selected_game %}

<script src="{% static 'js/search_results-jquery.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/results_page_v2.css' %}" />

{% endblock %}
{% block title %}Games Page{% endblock %}
{% block as_json %}
{% if request.GET.filters %}
    <li id="as_json_button"><a href='{% url "search_as_json" %}?q={{request.GET.q}}&filters={{request.GET.filters}}'>JSON</a></li>
{% else %}
    <li id="as_json_button"><a href='{% url "search_as_json" %}?q={{request.GET.q}}'>JSON</a></li>
{% endif %}
{% endblock %}
{% block content %}
<div class="col-xs-12 row content">
    {% for store in offline %}
    <p class="store-errors">Could not load data from {{store}}. Is it offline? Try again in few minutes.</p>
    {% endfor %}
    <span class="col-xs-9 titles">Title</span>
    <span class="col-xs-3 prices">Price(€)</span>
</div>
{% for r in output_list %}
<div class="col-xs-12 alldeals" id="alldeals{{r.faketitle}}">
    <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
    {% show_all_games store_query_list r.faketitle %}
    <div style="clear: both;"></div>
</div>
<div class="col-xs-12 row content">
    <div class="gamedeals">
        <span class="col-xs-9 titles"><a class="gametitle" ref="{{r.faketitle}}">{{ r.title }}</a></span>
        <span class="col-xs-3 prices"> {{ r.price|stringformat:".2f" }} </span>
    </div>
</div>
{% endfor %}

<div style="clear: both;"></div>
<div class="col-sm-12 sm-content">
    <table>
            <tr class="table-headers">
              <th>Game Title (Cheapest)</th>
              <th></th>
              <th>Store Link</th>
              <th>Original Price (€)</th>
              <th>Price (€)</th>
              <th>Discount %</th>
              <th>Platforms</th>
            </tr>

            {% for r in output_list %}

            <tr class="gamedeals">
              <td><a href='{{r.link}}' class="gametitle-sm" >{{ r.title }}</a></td>
              <td><button data-target="#modal-{{r.faketitle}}" data-toggle="modal" id={{r.faketitle}} class="btn btn-info btn-sm">View all</button></td>
              <td><a href="{{r.storelink}}">{{r.store}}</a></td>
              <td> {{ r.original_price|stringformat:".2f"  }} </td>
              <td> {{ r.price|stringformat:".2f" }} </td>
              <td> {{ r.discount }} </td>
              <td> {{ r.platforms }}</td>
            </tr>

            {% endfor %}
    </table>
    <br>

    {% for r in output_list %}
    <div id="modal-{{r.faketitle}}" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                    <h4>{{r.title}}</h4>
                </div>
                <div class="modal-body">
                    <table width="100%" class="table-modal">
                        <tr>
                          <th>Title</th>
                          <th>Store Link</th>
                          <th>Original Price</th>
                          <th>Price</th>
                          <th>Discount %</th>
                          <th>Platforms</th>
                        </tr>
                    {% show_all_games store_query_list r.faketitle %}
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
          </div>
    </div>
    {% endfor %}
    {% for store in offline %}
    <p class="store-errors">Could not load data from {{store}}. Is it offline? Try again in few minutes.</p>
    {% endfor %}
</div>
{% endblock %}